dist: bionic

dist: bionic
addons:
  apt:
    packages:
      - texlive-base
      - texlive-latex-extra
      - texlive-plain-generic
      - texlive-fonts-recommended
      - texlive-science
      - texlive-bibtex-extra
      - latexmk

jobs:
  include:
    - name: latex
      script:
        - cd lab_0/doc && latexmk -pdf
        - cd lab_1/doc && latexmk -pdf
